import { SharedLibsModule } from '../shared/shared-libs.module';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    InfoCompetenceAjouterComponent,
    InfoCompetenceSupprimerComponent,
    InfoCompetenceEvaluerComponent,
    InfoAdminOuComponent,
    InfoAdminPourquoiComponent,
    InfoAdminQuiComponent,
    InfoAdminBrancheAjouterComponent,
    InfoAdminBrancheSupprimerComponent,
    InfoAdminBrancheEditerComponent,
    InfoAdminCompetenceAjouterComponent,
    InfoAdminCompetenceEditerComponent,
    InfoAdminCompetenceSupprimerComponent,
    InfoFinderCritereSupprimerComponent,
    InfoFinderCritereAjouterComponent,
    InfoFinderQuoiComponent,
    InfoFinderQuiComponent,
    InfoFinderOuComponent,
    InfoFinderPourquoiComponent,
    InfoMatriceQuoiComponent,
    InfoMatriceOuComponent,
    InfoMatriceQuiComponent,
    InfoMatricePourquoiComponent,
    InfoGeneralCommentComponent,
    InfoGeneralQuoiComponent,
    InfoGeneralPourquoiComponent,
    InfoCompetenceAcquiseOuComponent,
    InfoCompetenceRequiseOuComponent,
    InfoCompetenceRequiseQuoiComponent,
} from './';


@NgModule({
    imports: [
        SharedLibsModule,
        CommonModule,
    ],
    declarations: [
        InfoCompetenceAjouterComponent,
        InfoCompetenceSupprimerComponent,
        InfoCompetenceEvaluerComponent,
        InfoAdminOuComponent,
        InfoAdminPourquoiComponent,
        InfoAdminQuiComponent,
        InfoAdminBrancheAjouterComponent,
        InfoAdminBrancheSupprimerComponent,
        InfoAdminBrancheEditerComponent,
        InfoAdminCompetenceAjouterComponent,
        InfoAdminCompetenceEditerComponent,
        InfoAdminCompetenceSupprimerComponent,
        InfoFinderCritereSupprimerComponent,
        InfoFinderCritereAjouterComponent,
        InfoFinderQuoiComponent,
        InfoFinderQuiComponent,
        InfoFinderOuComponent,
        InfoFinderPourquoiComponent,
        InfoMatriceQuoiComponent,
        InfoMatriceOuComponent,
        InfoMatriceQuiComponent,
        InfoMatricePourquoiComponent,
        InfoGeneralCommentComponent,
        InfoGeneralQuoiComponent,
        InfoGeneralPourquoiComponent,
        InfoCompetenceAcquiseOuComponent,
        InfoCompetenceRequiseQuoiComponent,
        InfoCompetenceRequiseOuComponent
    ],
    exports: [
        InfoCompetenceAjouterComponent,
        InfoCompetenceSupprimerComponent,
        InfoCompetenceEvaluerComponent,
        InfoAdminOuComponent,
        InfoAdminPourquoiComponent,
        InfoAdminQuiComponent,
        InfoAdminBrancheAjouterComponent,
        InfoAdminBrancheSupprimerComponent,
        InfoAdminBrancheEditerComponent,
        InfoAdminCompetenceAjouterComponent,
        InfoAdminCompetenceEditerComponent,
        InfoAdminCompetenceSupprimerComponent,
        InfoFinderCritereSupprimerComponent,
        InfoFinderCritereAjouterComponent,
        InfoFinderQuoiComponent,
        InfoFinderQuiComponent,
        InfoFinderOuComponent,
        InfoFinderPourquoiComponent,
        InfoMatriceQuoiComponent,
        InfoMatriceOuComponent,
        InfoMatriceQuiComponent,
        InfoMatricePourquoiComponent,
        InfoGeneralCommentComponent,
        InfoGeneralQuoiComponent,
        InfoGeneralPourquoiComponent,
        InfoCompetenceAcquiseOuComponent,
        InfoCompetenceRequiseOuComponent,
        InfoCompetenceRequiseQuoiComponent
    ]
})
export class InfoModule { }
